name: Generate space shooter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out generated-assets branch
        uses: actions/checkout@v6
        with:
          ref: output
          fetch-depth: 2

      - name: Generate space shooter animation
        uses: czl9707/gh-space-shooter@96d45ed9a790300da731b9fc49b95d697f528464 # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: gh-space-shooter.gif
          strategy: random
          fps: "25"
